[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'leanvec'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.1'
        primary = "float16"
        secondary = "float16"
        leanvec_dims = 160
        data_matrix = ''
        query_matrix = ''

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'leanvec'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.1'
        primary = "lvq8"
        secondary = "float16"
        leanvec_dims = 160
        data_matrix = ''
        query_matrix = ''

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'leanvec'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.1'
        primary = "lvq8"
        secondary = "lvq8"
        leanvec_dims = 160
        data_matrix = ''
        query_matrix = ''

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'leanvec'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.1'
        primary = "lvq8"
        secondary = "lvq8"
        leanvec_dims = 160
        data_matrix = 'dpr/leanvec/data_matrix_160.fvecs'
        query_matrix = 'dpr/leanvec/query_matrix_160.fvecs'
