[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'uncompressed'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.0'
        data_type = 'float16'

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = "sequential"

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = "turbo<16x4>"

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = "sequential"

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = "turbo<16x8>"

[[vamana_static_build]]
__version__ = 'v0.0.3'
description = 'dpr-1m'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
distance = 'MIP'
ndims = 768
num_threads = 72
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [vamana_static_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 8
        residual = 8
        strategy = "sequential"
