[[vamana_dynamic_build]]
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
dynamic_optimization = 'minimal'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
description = 'dpr-1m'
distance = 'MIP'
ndims = 768
num_neighbors = 10
num_threads = 72
target_recalls = [ 0.90 ]

    [vamana_dynamic_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dynamic_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    total_iterations = 20
    rng_seed = 0xc0ffee

        [vamana_dynamic_build.schedule.search_parameters]
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.9 ]

    [vamana_dynamic_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'uncompressed'

        [vamana_dynamic_build.dataset.dataset]
        __version__ = 'v0.0.0'
        data_type = 'float16'

[[vamana_dynamic_build]]
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
dynamic_optimization = 'minimal'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
description = 'dpr-1m'
distance = 'MIP'
ndims = 768
num_neighbors = 10
num_threads = 72
target_recalls = [ 0.9 ]

    [vamana_dynamic_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dynamic_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    total_iterations = 20
    rng_seed = 0xc0ffee

        [vamana_dynamic_build.schedule.search_parameters]
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.9 ]

    [vamana_dynamic_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = "sequential"

[[vamana_dynamic_build]]
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
dynamic_optimization = 'minimal'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
description = 'dpr-1m'
distance = 'MIP'
ndims = 768
num_neighbors = 10
num_threads = 72
target_recalls = [ 0.9 ]

    [vamana_dynamic_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dynamic_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    total_iterations = 20
    rng_seed = 0xc0ffee

        [vamana_dynamic_build.schedule.search_parameters]
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.9 ]

    [vamana_dynamic_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = "sequential"

[[vamana_dynamic_build]]
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
dynamic_optimization = 'minimal'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
description = 'dpr-1m'
distance = 'MIP'
ndims = 768
num_neighbors = 10
num_threads = 72
target_recalls = [ 0.9 ]

    [vamana_dynamic_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dynamic_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    total_iterations = 20
    rng_seed = 0xc0ffee

        [vamana_dynamic_build.schedule.search_parameters]
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.9 ]

    [vamana_dynamic_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 8
        residual = 8
        strategy = "sequential"

[[vamana_dynamic_build]]
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
dynamic_optimization = 'minimal'
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
description = 'dpr-1m'
distance = 'MIP'
ndims = 768
num_neighbors = 10
num_threads = 72
target_recalls = [ 0.9 ]

    [vamana_dynamic_build.build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dynamic_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 128
    prune_to = 124
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    total_iterations = 20
    rng_seed = 0xc0ffee

        [vamana_dynamic_build.schedule.search_parameters]
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.9 ]

    [vamana_dynamic_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = "turbo<16x8>"
