[[inverted_static_memory_build]]
__version__ = 'v0.0.1'
centroids_directory = ""
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_build_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
query_type = 'float32'
save_directory = ''
search_configs = []
strategy = 'sparse'

    [inverted_static_memory_build.clustering_parameters]
    __version__ = 'v0.0.0'
    batchsize = 100000
    epsilon = 1.0
    max_cluster_size = 0
    max_replicas = 7
    num_intermediate_results = 64
    percent_centroids = 0.12
    refinement_alpha = 0.95
    search_window_size = 50
    seed = 12648430

    [inverted_static_memory_build.primary_build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 64
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 60
    use_full_search_history = true
    window_size = 200

    [inverted_static_memory_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]

    [inverted_static_memory_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'uncompressed'

        [inverted_static_memory_build.dataset.dataset]
        __version__ = 'v0.0.0'
        data_type = 'float16'

[[inverted_static_memory_build]]
__version__ = 'v0.0.1'
centroids_directory = ""
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_build_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
query_type = 'float32'
save_directory = ''
search_configs = []
strategy = 'sparse'

    [inverted_static_memory_build.clustering_parameters]
    __version__ = 'v0.0.0'
    batchsize = 100000
    epsilon = 1.0
    max_cluster_size = 0
    max_replicas = 8
    num_intermediate_results = 64
    percent_centroids = 0.12
    refinement_alpha = 0.95
    search_window_size = 50
    seed = 12648430

    [inverted_static_memory_build.primary_build_parameters]
    __version__ = 'v0.0.1'
    alpha = 0.95
    graph_max_degree = 64
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 60
    use_full_search_history = true
    window_size = 200

    [inverted_static_memory_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.9 ]

    [inverted_static_memory_build.dataset]
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [inverted_static_memory_build.dataset.dataset]
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = "sequential"
