[inverted_test_generator]
__version__ = 'v0.0.0'
data_f32 = 'data_f32.fvecs'
queries_f32 = 'queries_f32.fvecs'
queries_in_training_set = 100

    [[inverted_test_generator.groundtruths]]
    __version__ = 'v0.0.0'
    distance = 'L2'
    path = 'groundtruth_euclidean.ivecs'

    [[inverted_test_generator.groundtruths]]
    __version__ = 'v0.0.0'
    distance = 'MIP'
    path = 'groundtruth_mip.ivecs'
